import { broadcastPaymentSync } from '@/hooks/useRealtimeSync'
import { getLocalWorkOrders } from '@/services/supabase/workOrders'
import { WorkOrderWorkflowService } from '@/services/workOrderWorkflowService'
import { pushEntityToCloud, broadcastCloudSync } from '@/services/cloudSyncService'
import { filterOutLegacyDemoItems } from '@/utils/legacyDemoPurge'
import type { WorkOrder } from '@/types/workOrders'
import type {
  PostProductionItem,
  DeliverableStatus,
  ClientApprovalStatus,
  DeliverableComment,
  DeliverableActivityLog,
} from '@/types/postProduction'

const STORAGE_KEY = 'trufocus_crm_post_production_v1'
const COMMENTS_KEY = 'trufocus_crm_deliverable_comments_v1'
const LOGS_KEY = 'trufocus_crm_deliverable_logs_v1'

/**
 * Check if a Work Order's shoot has been completed.
 * Work Orders appear in Post Production ONLY when production_completed === true
 * or all production services/events are completed.
 */
export function isWorkOrderProductionCompleted(wo: WorkOrder): boolean {
  if (wo.production_completed === true) return true

  const st = (wo.status || '').toLowerCase()
  if (st === 'editing' || st === 'completed' || st === 'delivered') return true

  const prodStatus = WorkOrderWorkflowService.calculateProductionStatus(wo)
  if (prodStatus === 'completed') return true

  return false
}

/**
 * Automatically expand package services into granular post-production deliverable tasks
 * upon shoot completion.
 */
export function getAutoGeneratedDeliverableNames(wo: WorkOrder): string[] {
  const existingDeliverables = (wo.deliverables || [])
    .filter((d) => d.is_included !== false)
    .map((d) => d.name)

  if (existingDeliverables.length > 0) {
    return existingDeliverables
  }

  const generated: string[] = []
  const eventTypes = (wo.events || []).map((e) => (e.event_type_name || wo.event_type || '').toLowerCase())

  generated.push('Raw Footage & Photos Uploaded')
  generated.push('Edited Photos')
  generated.push('Social Media Photos')
  generated.push('Album Selection')
  generated.push('Album Designing')
  generated.push('Gallery Upload')

  const isVideoRequested = eventTypes.some((t) => t.includes('video') || t.includes('film') || t.includes('wedding') || t.includes('cinematic'))
  if (isVideoRequested || true) {
    generated.push('Highlight Film')
    generated.push('Instagram Reel')
    generated.push('Full Length Video')
  }

  return generated
}

/**
 * Fetch Post Production items.
 * STRICT RULE: Only Work Orders where production_completed === true appear in Post Production.
 */
export function getPostProductionItems(): PostProductionItem[] {
  let storedItems: PostProductionItem[] = []
  try {
    const data = localStorage.getItem(STORAGE_KEY)
    if (data) {
      let parsed = JSON.parse(data)
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed) && Array.isArray((parsed as any).data)) {
        parsed = (parsed as any).data
      }
      if (Array.isArray(parsed)) {
        if (parsed.length > 0 && Array.isArray(parsed[0])) {
          parsed = parsed.flat()
        }
        const valid = parsed.filter((i: any) => i && typeof i === 'object' && i.id)
        storedItems = filterOutLegacyDemoItems(valid)
        if (storedItems.length !== valid.length) {
          localStorage.setItem(STORAGE_KEY, JSON.stringify(storedItems))
        }
      }
    }
  } catch (e) {
    console.error('Error reading post production items from storage', e)
  }

  const productionCompletedWorkOrders = getLocalWorkOrders().filter(
    (w) => !w.deleted_at && w.status !== 'deleted' && isWorkOrderProductionCompleted(w)
  )

  const taskMap = new Map<string, PostProductionItem>()
  storedItems.forEach((item) => {
    if (!item) return
    if (item.id) taskMap.set(item.id, item)
    if (item.work_order_id && item.deliverable_name) {
      taskMap.set(`${item.work_order_id}_${item.deliverable_name.toLowerCase()}`, item)
    }
    if (item.work_order_number && item.deliverable_name) {
      taskMap.set(`${item.work_order_number}_${item.deliverable_name.toLowerCase()}`, item)
    }
  })

  const derivedItems: PostProductionItem[] = []
  let hasNewGeneratedItems = false

  productionCompletedWorkOrders.forEach((wo) => {
    const deliverableNames = getAutoGeneratedDeliverableNames(wo)

    deliverableNames.forEach((delName, idx) => {
      const delNameLower = delName.toLowerCase()
      const key1 = `${wo.id}_${delNameLower}`
      const key2 = `${wo.work_order_number}_${delNameLower}`
      const existing = taskMap.get(key1) || taskMap.get(key2)

      if (existing) {
        derivedItems.push({
          ...existing,
          work_order_id: wo.id,
          work_order_number: wo.work_order_number,
          customer_name: wo.customer_name || existing.customer_name,
          mobile: wo.mobile || existing.mobile,
          event_type: wo.event_type || existing.event_type,
        })
      } else {
        hasNewGeneratedItems = true
        const newItem: PostProductionItem = {
          id: `post-${wo.id}-${idx}`,
          work_order_id: wo.id,
          work_order_number: wo.work_order_number,
          customer_name: wo.customer_name,
          mobile: wo.mobile,
          event_type: wo.event_type,
          deliverable_name: delName,
          specifications: `${delName} for ${wo.customer_name} (${wo.project_name})`,
          assigned_editor_name: null,
          assigned_editor_id: null,
          priority: 'medium',
          due_date: wo.final_delivery_date || wo.album_delivery_date || new Date().toISOString().split('T')[0],
          status: 'not_started',
          progress_percent: 0,
          approval_status: 'not_sent',
          created_at: wo.created_at || new Date().toISOString(),
          updated_at: new Date().toISOString(),
        }
        derivedItems.push(newItem)
      }
    })
  })

  // Also include any custom deliverables present in storedItems that belong to active work orders
  storedItems.forEach((item) => {
    if (item && item.id && !derivedItems.some((d) => d.id === item.id)) {
      derivedItems.push(item)
    }
  })

  if (hasNewGeneratedItems && derivedItems.length > 0) {
    savePostProductionItems(derivedItems)
  }

  return derivedItems
}

/**
 * Task Dependency Checkers
 */

// 1. Gallery Upload requires Edited Photos to be completed
export function isGalleryUploadBlocked(item: PostProductionItem, allWOItems: PostProductionItem[]): { blocked: boolean; reason?: string } {
  if (!item.deliverable_name.toLowerCase().includes('gallery upload')) {
    return { blocked: false }
  }
  const editedPhotosItem = allWOItems.find(
    (i) => i.work_order_id === item.work_order_id && i.deliverable_name.toLowerCase().includes('edited photos')
  )
  if (editedPhotosItem && editedPhotosItem.status !== 'completed' && editedPhotosItem.status !== 'delivered' && editedPhotosItem.status !== 'done') {
    return {
      blocked: true,
      reason: 'Requires "Edited Photos" to be completed before Gallery Upload can begin.',
    }
  }
  return { blocked: false }
}

// 2. Album Design requires Client Selected Photos to be completed
export function isAlbumDesignBlocked(item: PostProductionItem, allWOItems: PostProductionItem[]): { blocked: boolean; reason?: string } {
  if (!item.deliverable_name.toLowerCase().includes('album design')) {
    return { blocked: false }
  }
  const selectionItem = allWOItems.find(
    (i) => i.work_order_id === item.work_order_id && (i.deliverable_name.toLowerCase().includes('selection') || i.deliverable_name.toLowerCase().includes('edited photos'))
  )
  if (selectionItem && selectionItem.status !== 'completed' && selectionItem.status !== 'delivered' && selectionItem.status !== 'done') {
    return {
      blocked: true,
      reason: 'Requires "Album Selection" to be completed by client before Album Designing can begin.',
    }
  }
  return { blocked: false }
}

// 3. Cinematic Film / Highlight / Reel / Trailer requires Raw Footage Uploaded to be completed
export function isCinematicFilmBlocked(item: PostProductionItem, allWOItems: PostProductionItem[]): { blocked: boolean; reason?: string } {
  const name = item.deliverable_name.toLowerCase()
  if (!name.includes('highlight') && !name.includes('reel') && !name.includes('trailer') && !name.includes('full length video')) {
    return { blocked: false }
  }
  const rawFootageItem = allWOItems.find(
    (i) => i.work_order_id === item.work_order_id && i.deliverable_name.toLowerCase().includes('raw footage')
  )
  if (rawFootageItem && rawFootageItem.status !== 'completed' && rawFootageItem.status !== 'delivered' && rawFootageItem.status !== 'done') {
    return {
      blocked: true,
      reason: 'Requires "Raw Footage & Photos Uploaded" to be completed before Video Editing can begin.',
    }
  }
  return { blocked: false }
}

export function savePostProductionItems(items: PostProductionItem[]): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(items))
    pushEntityToCloud('post_production', 'main', items)
    broadcastCloudSync('post_production', items)
    broadcastPaymentSync()
    WorkOrderWorkflowService.reconcileAllLifecycles()
  } catch (e) {
    console.error('Error saving post production items to storage', e)
  }
}

export function updateDeliverableStatus(
  id: string,
  newStatus: DeliverableStatus,
  progressPercent?: number
): PostProductionItem | null {
  const items = getPostProductionItems()
  const idx = items.findIndex((i) => i.id === id)
  if (idx === -1) return null

  const target = items[idx]
  let autoProgress = progressPercent ?? target.progress_percent

  if (newStatus === 'completed' || newStatus === 'delivered' || newStatus === 'done') {
    autoProgress = 100
  } else if (newStatus === 'client_approval') {
    autoProgress = 90
  } else if (newStatus === 'ready_for_review' || newStatus === 'review' || newStatus === 'for_review') {
    autoProgress = 75
  } else if (newStatus === 'in_progress' || newStatus === 'editing') {
    autoProgress = 40
  } else if (newStatus === 'not_started' || newStatus === 'pending' || newStatus === 'assigned') {
    autoProgress = 0
  }

  const updated: PostProductionItem = {
    ...target,
    status: newStatus,
    progress_percent: autoProgress,
    delivered_date: newStatus === 'delivered' ? new Date().toISOString().split('T')[0] : target.delivered_date,
    updated_at: new Date().toISOString(),
  }

  items[idx] = updated
  savePostProductionItems(items)
  WorkOrderWorkflowService.syncWorkOrderStatus(target.work_order_id)

  addDeliverableActivityLog(
    id,
    `Status changed from ${target.status.replace('_', ' ').toUpperCase()} to ${newStatus.replace('_', ' ').toUpperCase()}`,
    'Editor'
  )

  return updated
}

export function updateDeliverableApproval(
  id: string,
  approvalStatus: ClientApprovalStatus
): PostProductionItem | null {
  const items = getPostProductionItems()
  const idx = items.findIndex((i) => i.id === id)
  if (idx === -1) return null

  const target = items[idx]
  const updated: PostProductionItem = {
    ...target,
    approval_status: approvalStatus,
    updated_at: new Date().toISOString(),
  }

  items[idx] = updated
  savePostProductionItems(items)
  WorkOrderWorkflowService.syncWorkOrderStatus(target.work_order_id)

  addDeliverableActivityLog(id, `Client approval status updated to ${approvalStatus}`, 'Manager')
  return updated
}

export function updateDeliverableAssignment(
  id: string,
  editorName: string,
  editorId?: string
): PostProductionItem | null {
  const items = getPostProductionItems()
  const idx = items.findIndex((i) => i.id === id)
  if (idx === -1) return null

  const target = items[idx]
  const previousEditor = target.assigned_editor_name
  const previousStatus = target.status

  let newStatus = target.status
  let newProgress = target.progress_percent

  if (editorName && editorName.trim().length > 0) {
    if (!previousEditor) {
      if (previousStatus === 'not_started' || previousStatus === 'pending' || previousStatus === 'assigned') {
        newStatus = 'in_progress'
        newProgress = 40
      }
      addDeliverableActivityLog(id, `Deliverable assigned to ${editorName}`, 'Manager')
      if (previousStatus !== newStatus) {
        addDeliverableActivityLog(id, `Status changed from Not Started to In Progress`, 'System')
      }
    } else if (previousEditor !== editorName) {
      if (previousStatus === 'not_started') {
        newStatus = 'in_progress'
        newProgress = 40
      }
      addDeliverableActivityLog(id, `Reassigned from ${previousEditor} to ${editorName}`, 'Manager')
    }
  } else {
    newStatus = 'not_started'
    newProgress = 0
    addDeliverableActivityLog(id, `Assignment removed`, 'Manager')
    if (previousStatus !== 'not_started') {
      addDeliverableActivityLog(id, `Status changed from ${previousStatus.replace('_', ' ').toUpperCase()} to Not Started`, 'System')
    }
  }

  const updated: PostProductionItem = {
    ...target,
    assigned_editor_name: editorName || null,
    assigned_editor_id: editorName ? (editorId || target.assigned_editor_id) : null,
    status: newStatus,
    progress_percent: newProgress,
    updated_at: new Date().toISOString(),
  }

  items[idx] = updated
  savePostProductionItems(items)
  WorkOrderWorkflowService.syncWorkOrderStatus(target.work_order_id)

  return updated
}

export function updateDeliverableGallery(
  id: string,
  galleryUrl: string,
  password?: string,
  expiryDate?: string
): PostProductionItem | null {
  const items = getPostProductionItems()
  const idx = items.findIndex((i) => i.id === id)
  if (idx === -1) return null

  const target = items[idx]
  const updated: PostProductionItem = {
    ...target,
    gallery: {
      url: galleryUrl,
      password: password || target.gallery?.password,
      expiryDate: expiryDate || target.gallery?.expiryDate,
    },
    status: 'delivered',
    progress_percent: 100,
    delivered_date: new Date().toISOString().split('T')[0],
    updated_at: new Date().toISOString(),
  }

  items[idx] = updated
  savePostProductionItems(items)
  WorkOrderWorkflowService.syncWorkOrderStatus(target.work_order_id)

  addDeliverableActivityLog(id, `Gallery URL published: ${galleryUrl}`, 'Editor')
  return updated
}

export function addDeliverableComment(
  deliverableId: string,
  userName: string,
  role: string,
  content: string
): DeliverableComment {
  const all = getDeliverableCommentsMap()
  const current = all[deliverableId] || []
  const newComment: DeliverableComment = {
    id: `comm-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
    deliverable_id: deliverableId,
    user_name: userName,
    role,
    content,
    created_at: new Date().toISOString(),
  }
  all[deliverableId] = [newComment, ...current]

  try {
    localStorage.setItem(COMMENTS_KEY, JSON.stringify(all))
    broadcastPaymentSync()
  } catch (e) {
    console.error('Error saving comment', e)
  }

  addDeliverableActivityLog(deliverableId, `New comment added by ${userName}`, userName)
  return newComment
}

export function getDeliverableComments(deliverableId: string): DeliverableComment[] {
  const all = getDeliverableCommentsMap()
  return all[deliverableId] || []
}

function getDeliverableCommentsMap(): Record<string, DeliverableComment[]> {
  try {
    const d = localStorage.getItem(COMMENTS_KEY)
    return d ? JSON.parse(d) : {}
  } catch {
    return {}
  }
}

export function getDeliverableActivityLogs(deliverableId: string): DeliverableActivityLog[] {
  try {
    const d = localStorage.getItem(LOGS_KEY)
    const map: Record<string, DeliverableActivityLog[]> = d ? JSON.parse(d) : {}
    return map[deliverableId] || []
  } catch {
    return []
  }
}

export function addDeliverableActivityLog(
  deliverableId: string,
  action: string,
  userName: string
): void {
  try {
    const d = localStorage.getItem(LOGS_KEY)
    const map: Record<string, DeliverableActivityLog[]> = d ? JSON.parse(d) : {}
    const current = map[deliverableId] || []
    const newLog: DeliverableActivityLog = {
      id: `log-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
      deliverable_id: deliverableId,
      action,
      user_name: userName,
      timestamp: new Date().toISOString(),
    }
    map[deliverableId] = [newLog, ...current]
    localStorage.setItem(LOGS_KEY, JSON.stringify(map))
  } catch (e) {
    console.error('Error saving activity log', e)
  }
}
